# UAV Temporal Motion Dataset Configuration
# Variables for path configuration
IMG_FOLDER: "c:/data/processed_anti_uav_v2/images"
TRAIN_SEQ_FILE: "c:/data/processed_anti_uav_v2/sequences/train.txt"
VAL_SEQ_FILE: "c:/data/processed_anti_uav_v2/sequences/val.txt"

# Task
task: detection

# Training dataloader
train_dataloader:
  type: DataLoader
  dataset:
    type: UAVTemporalMotionDataset
    img_folder: "c:/data/processed_anti_uav_v2/images"
    seq_file: "c:/data/processed_anti_uav_v2/sequences/train.txt"
    seq_len: 5
    transforms:
      type: Compose
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: True
  batch_size: 4
  num_workers: 4
  collate_fn: uav_temporal_motion_collate_fn

# Validation dataloader
val_dataloader:
  type: DataLoader
  dataset:
    type: UAVTemporalMotionDataset
    img_folder: "c:/data/processed_anti_uav_v2/images"
    seq_file: "c:/data/processed_anti_uav_v2/sequences/val.txt"
    seq_len: 5
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
  shuffle: False
  batch_size: 8
  num_workers: 4
  collate_fn: uav_temporal_motion_collate_fn
