# RT-DETR ResNet-34 6x schedule on UAV non-temporal dataset
__include__:
  - '../dataset/uav_nontemporal.yml'       # custom UAV non-temporal dataset
  - '../runtime.yml'                       # runtime settings (AMP, EMA, sync_bn)
  - './rtdetr_r34vd_6x_coco.yml'            # model backbone, transformer, optimizer defaults

# Output & training schedule
output_dir: ./output/uav_nontemporal_r34vd
epoches: 25
log_step: 10
checkpoint_step: 5

# Backbone override
PResNet:
  depth: 34
  pretrained: True
HybridEncoder:
  in_channels: [128, 256, 512]
