__include__: [include/rtdetr_dla34.yml, include/dataloader.yml, include/optimizer.yml, ../dataset/uav_temporal_detection.yml]

output_dir: ./output/uav_temporal_rtdetr_dla34

# Override epochs for testing
epochs: 1

# Disable pretrained weights for testing
DLANet:
  pretrained: False
