# UAV Temporal Detection Configuration
# Integrates temporal motion detection into RT-DETR pipeline

__include__: [
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
]

task: uav_temporal_detection
output_dir: ./output/uav_temporal_rtdetr_dla34_integrated

epochs: 1
num_classes: 1
use_focal_loss: True

# Model configuration - using the same pattern as the base rtdetr configs
model: TemporalRTDETR
criterion: SetCriterion
postprocessor: RTDETRPostProcessor

# Temporal RT-DETR configuration (instead of standard RTDETR)
TemporalRTDETR:
  backbone: DLANet
  encoder: HybridEncoder
  decoder: RTDETRTransformer
  use_motion: True
  motion_t_window: 5
  motion_in_channels: 3

# Backbone configuration (same as DLA34)
DLANet:
  dla: dla34
  pretrained: False  # Cannot use pretrained weights with modified input channels
  return_idx: [1, 2, 3]

# Encoder configuration
HybridEncoder:
  in_channels: [128, 256, 512]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1
  act: 'silu'
  eval_spatial_size: [512, 640]

# Decoder configuration
RTDETRTransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_queries: 300
  num_decoder_layers: 6
  num_denoising: 100
  eval_idx: -1
  eval_spatial_size: [512, 640]

# Criterion configuration
SetCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2}
  losses: ['vfl', 'boxes']
  alpha: 0.75
  gamma: 2.0
  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0

# Postprocessor configuration
RTDETRPostProcessor:
  num_classes: 1
  num_top_queries: 300

# Dataset configuration for UAV temporal sequences
train_dataloader:
  type: DataLoader
  dataset:
    type: UAVTemporalMotionDataset
    img_folder: c:/data/processed_anti_uav_v2/images
    seq_file: c:/data/processed_anti_uav_v2/sequences/train.txt
    seq_len: 5
    motion_enabled: True
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4  # Smaller batch for temporal sequences
  num_workers: 4
  collate_fn: uav_temporal_motion_collate_fn
  drop_last: True

val_dataloader:
  type: DataLoader  
  dataset:
    type: UAVTemporalMotionDataset
    img_folder: c:/data/processed_anti_uav_v2/images
    seq_file: c:/data/processed_anti_uav_v2/sequences/val.txt
    seq_len: 5
    motion_enabled: True
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  batch_size: 4
  num_workers: 4
  collate_fn: uav_temporal_motion_collate_fn
  drop_last: False
