# UAV Temporal RT-DETR Configuration with correct image dimensions
# Inherits from base RT-DETR DLA34 configuration but overrides spatial sizes

__include__: [include/rtdetr_dla34.yml, include/dataloader.yml, include/optimizer.yml, ../dataset/uav_temporal_detection.yml]

output_dir: ./output/uav_temporal_rtdetr_dla34

# Override epochs for testing
epochs: 10

# UAV dataset specific settings
num_classes: 1

# Fix spatial dimensions to match UAV dataset (512x640)
HybridEncoder:
  in_channels: [128, 256, 512]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1
  act: 'silu'
  # Fix spatial size for UAV images
  eval_spatial_size: [512, 640]

RTDETRTransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_queries: 300
  num_decoder_layers: 6
  num_denoising: 100
  eval_idx: -1
  # Fix spatial size for UAV images
  eval_spatial_size: [512, 640]

# Support variable input sizes including our 512x640 images
RTDETR: 
  backbone: DLANet
  encoder: HybridEncoder
  decoder: RTDETRTransformer
  multi_scale: [512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512, 512]  # Fixed size for UAV

# Disable pretrained weights for testing
DLANet:
  pretrained: False
